name: Acceptance Tests

on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create compose stack
        run: docker-compose -f docker-compose.ci.yml up -d --build --force-recreate

      - name: Compile and run acceptance tests
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism make all build acceptance-run-chromium

      - name: "Look for screenshots"
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism find frontend/tests/acceptance/screenshots/
        if: always()

      - name: Copy screenshots from container to host
        run: docker compose -f docker-compose.ci.yml cp photoprism:/go/src/github.com/photoprism/photoprism/frontend/tests/acceptance/screenshots/ screenshots/
        if: always()

      - name: Tear down stack
        run: docker-compose -f docker-compose.ci.yml down

      - uses: actions/upload-artifact@v3
        if: always()
        continue-on-error: true
        with:
          name: screenshots
          path: screenshots/
