name: Acceptance Tests

on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create compose stack
        run: docker-compose up -d --build --force-recreate

      - name: Compile and run acceptance tests
        run: docker-compose exec -T photoprism make all build acceptance-prepare acceptance-run-chromium

      - name: Tear down stack
        run: docker-compose down

      - uses: actions/upload-artifact@v3
        if: always()
        continue-on-error: true
        with:
          name: screenshots
          path: frontend/tests/screenshots/
