name: Acceptance Tests

on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targets:
          - acceptance-auth-run-chromium
          - acceptance-public-run-chromium
          - acceptance-run-chromium-short
          - acceptance-run-chromium

    steps:
      - uses: actions/checkout@v3

      - name: Create compose stack
        run: docker-compose -f docker-compose.ci.yml up -d --build --force-recreate

      - name: Compile and run acceptance tests
        id: acceptance_tests
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism make all build ${{ matrix.targets }}

      - name: Look for screenshots
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism find frontend/tests/acceptance/screenshots/
        if: always() && steps.acceptance_tests.outcome == 'failure'

      - name: Copy screenshots from container to host
        run: docker compose -f docker-compose.ci.yml cp photoprism:/go/src/github.com/photoprism/photoprism/frontend/tests/acceptance/screenshots/ screenshots/
        if: always() && steps.acceptance_tests.outcome == 'failure'

      - name: Look for videos
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism find frontend/tests/acceptance/videos/
        if: always() && steps.acceptance_tests.outcome == 'failure'

      - name: Copy videos from container to host
        run: docker compose -f docker-compose.ci.yml cp photoprism:/go/src/github.com/photoprism/photoprism/frontend/tests/acceptance/videos/ videos/
        if: always() && steps.acceptance_tests.outcome == 'failure'

      - name: Tear down stack
        run: docker-compose -f docker-compose.ci.yml down

      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        if: always() && steps.acceptance_tests.outcome == 'failure'
        continue-on-error: true
        with:
          name: screenshots-${{ matrix.targets }}
          path: screenshots/

      - name: Archive videos
        uses: actions/upload-artifact@v3
        if: always() && steps.acceptance_tests.outcome == 'failure'
        continue-on-error: true
        with:
          name: videos-${{ matrix.targets }}
          path: videos/
