on:
  pull_request:
    paths:
      - "ext/**"

jobs:
  publish-plugin-docker-images:
    strategy:
      fail-fast: false
      matrix:
        plugins:
          - realesrgan
          - yolo8

    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed: 'ext/${{ matrix.plugins }}/**'

      - name: Checkout
        if: steps.changes.outputs.changed == 'true'
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: steps.changes.outputs.changed == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ext/realesrgan
          tags: kvalev/realesrgan:0.3.0
          push: true
